### PR TITLE
Support formnovalidate new

### PR DESCRIPTION
**Pull request by runephilosof**
I can't get the tests to run properly.
No matter what I do they run the original tests (I tried deleting them all, but they still ran).
So I haven't been able to see whether the test works.

I would have also made a test for the non-remote case, but since I couldn't run the tests, I didn't.

I started out with the v1.0.4 tag, since I need this for a rails 3.2.22 project.
That is the reason for the merge commit.

### CODE REVIEW

**Comment by runephilosof** [comment]
Fixes #316

**Comment by runephilosof** [comment]
There. Now the tests pass.

**Comment by rafaelfranca** [comment]
Looks good. Could you squash your commits?

**Comment by rafaelfranca** [comment]
Merged in 2aed62cdeec229914869bb0aa85eb5419f79d253. Thanks

**Pull request closed without merging**
