### PR TITLE
Added package.json

### PR DESCRIPTION
**Pull request by callumacrae**
Please push this project to npm! :-)

### CODE REVIEW

**Comment by justin808** [comment]
@josevalim @rafaelfranca This is really useful for us here: 

https://github.com/shakacode/react-webpack-rails-tutorial/pull/88

My new company will take over this. Let's figure out how we can work together.

Going forward, there's no comparison with using Webpack and NPM for JavaScript.

Please see this article I wrote on the topic: http://www.railsonmaui.com/blog/2014/10/03/integrating-webpack-and-the-es6-transpiler-into-an-existing-rails-project/

BTW, I met your team at RailsConf 2014. I didn't make 2015, as I've been insanely slammed setting up my new company ShakaCode based around combining Rails + React with Webpack.

**Comment by justin808** [comment]
FWIW, I just wrote up some options on integrating jQuery and jquery-ujs with Rails + Webpack: http://forum.railsonmaui.com/t/considerations-for-jquery-with-rails-and-webpack/344

**Comment by rafaelfranca** [comment]
My reasons to not publish a npm package are still the same. I'm also aligned with what [zepto.js maintainers think](https://github.com/madrobby/zepto/issues/1076).

> Let's figure out how we can work together.

Sure! I don't have any problem to someone on the community register and maintain a npm package but I don't think we are going to make that official or part of our release process.

**Comment by justin808** [comment]
@rafaelfranca I'll handle the publishing. I'll also check that the package.json works and provide good instructions. Would it be better to merge in a small number of changes so I don't have merge every time before publishing? Right now, I see only a small change to the readme to mention the alternative way of using this, and the addition of the package.json file, both of which should not affect you or other users.

**Comment by rafaelfranca** [comment]
Doing both changes (README mention and adding package.json) means that the support it is official what is exactly what I want to avoid. Is not possible to publish a package on npm without having to change the repository?

**Comment by justin808** [comment]
I can publish from a fork. I'm just wondering if that's going to be more confusing to the public. Possibly you can add me and another team members as backups that can support this?

For what it's worth, Webpack is increasingly popular and advocates using only npm (for client or server js). We really enjoy using npm to manage JavaScript dependencies. It's as if we used to put rails gems in our our git repos and now we have Gemfile and Gemfile.lock (package.json and npm-shrinkwrap.json). I also have had zero other JS projects requiring bower.

**Comment by rafaelfranca** [comment]
I really don't want to make official (and require the Rails team to do extra work) to something that is not advocate for Rails applications.

We don't use and we don't recommend to use Webpack. Our assets pipeline uses Sprockets and it is the recommended way. We want to make possible to others chose their tools, but we also reserve our choice to not have extra work for things that we don't want to recommend.

Adding official support to this repository means that if something goes wrong with the npm setup we will have to fix, and that is not something that we want to do. Of course there are people wanting to maintain this but who guarantees that they will stick around? If they left who will have to maintain this?

For me, this is the same as requiring us to maintain rspec-rails even if the Rails default stack is using minitest.

**Comment by justin808** [comment]
@rafaelfranca how about something to the effect of a pointer in the readme if one wants to use NPM? We could do that next to the info on bower?

**Comment by nozpheratu** [comment]
@callumacrae @justin808 Thanks folks. Now I have CSRF protection with my latest Webpack + Rails project. :)

**Comment by justin808** [comment]
@nozpheratu Are you using React on Rails?

**Comment by nozpheratu** [comment]
@justin808 I'm using Rails + Backbone + Marionette.

**Pull request closed without merging**
